version: '3.8'

services:
  db:
    image: mysql:latest
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
     - db_data:/var/lib/mysql
     - ./migrations:/docker-entrypoint-initdb.d
    restart: always

volumes:
  db_data:
    driver: local
